### ISSUE TITLE
Privoxy not working out of box

### ISSUE THREAD

**Issue by andjelx** [dperson/torproxy#11]
I have found that part `sed -i 's|\(127.0.0.1\|localhost\):8118|0.0.0.0:8118|' /etc/privoxy/config` in *Dockerfile* is not working out of box.
Have changed it to:` sed -i 's|\(127.0.0.1\):8118|0.0.0.0:8118|' /etc/privoxy/config`

**Comment by dperson** [comment]
Thank you for the report, it seemed like a fun idea to build the image, but I seldom use it. I really need to setup some automated testing...

The issue should be fixed now.
