### ISSUE TITLE
Privoxy not starting out-of the box

### ISSUE THREAD

**Issue by miraenator** [dperson/torproxy#12]
Hi, I've tried to start the privoxy. It did not work (tested with curl example).

When tried to run it manually, the following error message appeared:
```2017-03-21 10:25:54.976 7f204f467300 Info: Program name: privoxy
2017-03-21 10:25:54.982 7f204f467300 Fatal error: can't bind to :::8118: There may be another Privoxy or some other proxy running on port 8118
```
Of course, this was not true, nothing was running on the port (checked with netstat). This was related to IPV6, simple fix was to delete this line from ```/etc/privoxy/config``` and let it use only IPV4.

The netconfig is:
```
# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
274: eth0: <BROADCAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:87 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.135/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:87/64 scope link 
       valid_lft forever preferred_lft forever
```

I'm using debian-jessie (current) with docker.

thanx for fixing

m.

**Comment by dperson** [comment]
Thank you for the report! I set it up a while ago but haven't really used it much. I don't know how long it's been broken. I just pushed an update that should fix it.
