### ISSUE TITLE
Privoxy error

### ISSUE THREAD

**Issue by lukemaxwell** [dperson/torproxy#13]
The latest image is complaining about a misconfiguration of the privoxy listen-address:

`Error: Ignoring unrecognized directive '[::]:8118' (41319776U) in line 784 in configuration file (/etc/privoxy/config).`

Amending line 784 of /etc/privoxy/config from `[::]:8118` to `listen-address [::]:8118` fixed it.

**Comment by dperson** [comment]
Thank you very much for the report. It should be fixed now.
