### ISSUE TITLE
Configuration is broken if project name starts with "tor" and links are used

### ISSUE THREAD

**Issue by iBobik** [dperson/torproxy#15]
If I use links between torproxy and another service it will expose env variables of linked service into torproxy container. It is not problem unless compose project name starts with "tor", because then there will be env variables `TOR_*` and this variables will be copied into `/etc/tor/torrc`.

Then tor will fail on broken config:
```
21. 5. 2017 1:35:36May 21 01:35:36.957 [notice] Tor 0.2.9.10 (git-e28303bcf90b842d) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.1.0e and Zlib 1.2.8.
21. 5. 2017 1:35:36May 21 01:35:36.960 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
21. 5. 2017 1:35:36May 21 01:35:36.961 [notice] Read configuration file "/etc/tor/torrc".
21. 5. 2017 1:35:36May 21 01:35:36.974 [warn] Failed to parse/validate config: Unknown option '_DOWNLOADER_DB_1_ENV_GOSU_VERSION'.  Failing.
21. 5. 2017 1:35:36May 21 01:35:36.975 [err] Reading config failed--see warnings above.
```

**Comment by dperson** [comment]
Okay, tor uses camelCase for it's configuration option names. I've modified the entry point script to skip any named values starting with `tor_` that contain a second (or more) underscore character(s). Hopefully this will fix the issue you're seeing.

**Comment by iBobik** [comment]
Links use many many underscores, so it seems like a clever solution. :-)



Honza Pobořil
https://honza.poboril.cz

**Comment by renozion** [comment]
hello, I am stuck on this error, cant find solution: Failed to parse/validate config: Unknown option 'service'.  Failing.
any clues?
