### ISSUE TITLE
Allow the use of the control port

### ISSUE THREAD

**Issue by slampenny** [dperson/torproxy#16]
It looks like you've set up a control port in the dockerfile at 9051. It would be great if you could add a hashedpassword environment variable so that we can trigger a new tor circuit through that port using a python command such as:

```
from stem import Signal
from stem.control import Controller
with Controller.from_port(port = 9051) as controller:
    controller.autenticate()
    controller.signal(Signal.NEWNYM)
```

**Comment by dperson** [comment]
Okay, it should be in the new version that I just pushed, thanks for the suggestion.

**Comment by slampenny** [comment]
Wow. That what fast. You rock! Thanks!
