### ISSUE TITLE
Routing all host traffic doesn't work out of the box

### ISSUE THREAD

**Issue by adek05** [dperson/torproxy#18]
I started docker container you provide to setup proxy: 

```
docker run -it -p 8118:8118 -p 9050:9050 -d dperson/proxy
```

And then run the script `tor-route-all-traffic.sh` on the host (not container). Problems which I have is
1) DNS resolution doesn't work
2) Even if I disable entries in iptables which route DNS traffic through the proxy, still curl cannot connect to websites via proxy.

Is there some extra tuning needed to the script/docker run command to make it work?

**Comment by adek05** [comment]
I've debugged the problem. I had to run container with --net=host for routing to work. Feel free to close if you don't think update to the documentation is needed.

**Comment by dperson** [comment]
I think that I will update the documentation to make it more clear. Thanks.
