### ISSUE TITLE
Script generates garbage in torrc

### ISSUE THREAD

**Issue by alfonder** [dperson/torproxy#19]
I use the next script for container creating:
```
#!/bin/sh
DOCKER="sudo docker"

$DOCKER run -d \
	--restart=always \
	--name tor \
	-p 9050:9050 \
	-e PASSWORD="password" \
	-e LOCATION="DE},{US},{CA},{DE},{GB},{FR},{NL},{AT},{AU},{NO},{MX" \
	dperson/torproxy
```
Then the container restarts sequentially.
So I learned logs and config and discovered that torrc has many garbage strings in it. See the generated config file in attachment.

[torrc.gz](https://github.com/dperson/torproxy/files/1362879/torrc.gz)

**Comment by dperson** [comment]
Thanks for the report, it should be fixed now.
