### ISSUE TITLE
Problems with 301

### ISSUE THREAD

**Issue by marcelinhov2** [dperson/torproxy#22]
Hey, I'd try to run up an EC2 with your docker image.

When I did the curl test at my localhost and I got this:
![image](https://user-images.githubusercontent.com/232648/33573868-5432b632-d91e-11e7-95b0-56eaf5fd2bee.png)

What I'd run:
```sudo docker run -it -p 8118:8118 -p 9050:9050 -d dperson/torproxy -l US```

Did I make anything wrong?

**Comment by marcelinhov2** [comment]
![image](https://user-images.githubusercontent.com/232648/33574007-d0903cc2-d91e-11e7-8551-2f7b067227aa.png)

**Comment by marcelinhov2** [comment]
I'd solved my Google Crawler using the flag ```--net=host```, but the 301 error still for me.

If you wanna close, it's ok for me.

**Comment by marcelinhov2** [comment]
Thanks for your project, God bless yourself hahahahahhahaha... I gonna keep 500USD/month at my wallet s2

**Comment by dperson** [comment]
It looks fine to me. The only thing I'd say is are you sure of the IP that you're connecting to the proxy at? It's easy to typo. I've confirmed that the exact command works for me (no 301 redirect):
````
curl -x http://localhost:8118 -L http://jsonip.com                                  
{"ip":"95.130.11.216","about":"/about","Pro!":"http://getjsonip.com","reject-fascism":"Support Planned Parenthood: https://www.plannedparenthood.org/get-involved"}
```

**Comment by marcelinhov2** [comment]
@dperson Maybe you need to add this ```-L``` flag at your docs, am I right? Or it need to work without that too?

![image](https://user-images.githubusercontent.com/232648/33575412-b0daa9d0-d923-11e7-9e56-765affe185cc.png)

**Comment by dperson** [comment]
Done.
