### ISSUE TITLE
Issues Running Dockerized Torproxy

### ISSUE THREAD

**Issue by superphly** [dperson/torproxy#25]
I'm using this line to execute the torproxy:

docker run --name tor -it -p 8118:8118 -p 9050:9050 -d -v /var/local/tor/etc:/etc -v /var/local/tor/var/lib/tor:/var/lib/tor -e TORUSER=root dperson/torproxy -b 100

And this is the output from `docker logs tor`

May 14 01:07:44.342 [notice] Tor 0.3.1.9 (git-727d3f1b5e6eeda7) running on Linux with Libevent 2.1.8-stable, OpenSSL LibreSSL 2.6.3, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
May 14 01:07:44.342 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
May 14 01:07:44.342 [notice] Read configuration file "/etc/tor/torrc".
May 14 01:07:44.348 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
May 14 01:07:44.348 [warn] You specified a public address '0.0.0.0:9040' for TransPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
May 14 01:07:44.349 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
May 14 01:07:44.349 [warn] You specified a public address '0.0.0.0:9040' for TransPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
May 14 01:07:44.350 [notice] Opening Socks listener on 0.0.0.0:9050
May 14 01:07:44.350 [notice] Opening DNS listener on 127.0.0.1:5353
May 14 01:07:44.350 [notice] Opening Transparent pf/netfilter listener on 0.0.0.0:9040
May 14 01:07:44.351 [notice] Opening Control listener on 127.0.0.1:9051
May 14 01:07:44.351 [warn] Error setting configured user: tor not found
May 14 01:07:44.351 [warn] Failed to parse/validate config: Problem with User value. See logs for details.
May 14 01:07:44.351 [err] Reading config failed--see warnings above.

Any thoughts?

**Comment by dperson** [comment]
Don't set `-e TORUSER=root`?
