### ISSUE TITLE
Speed message

### ISSUE THREAD

**Issue by IvanTurgenev** [dperson/torproxy#27]
We were built to run on a 64-bit CPU, with OpenSSL 1.0.1 or later, but with a version of OpenSSL that apparently lacks accelerated support for the NIST P-224 and P-256 groups. Building openssl with such support (using the enable-ec_nistp_64_gcc_128 option when configuring it) would make ECDH much faster.

**Comment by dperson** [comment]
It's built by the upstream Alpine, so I'd recommend that you contact them.
