### ISSUE TITLE
torproxy.sh: line 66: warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by RockYuan** [dperson/torproxy#29]
/ # torproxy.sh -n
/usr/bin/torproxy.sh: line 66: warning: command substitution: ignored null byte in input
515 Authentication failed: Wrong length on authentication cookie.
Service already running, please restart container to apply changes

Thanks for your help !

**Comment by dperson** [comment]
Try running:
```
torproxy.sh -n echo "done"
```

I don't really use the newnym option, just let them timeout every 10 minutes. This was added by request, but the script should probably exit after telling tor to use a newnym. If the above fixes it, I'll make a change to the script.

**Comment by RockYuan** [comment]
`torproxy.sh -n -p ""`

This work ! Thank you !

**Comment by RockYuan** [comment]
Another question: 
how to change ip immediately via Control Port 9051 ?
[doc](https://www.torproject.org/docs/tor-manual.html.en#ControlPort)

**Comment by PowerToThePeople111** [comment]
> torproxy.sh -n echo "done"

That worked for me, actually. 

> torproxy.sh -n -p ""

This sadly not.

**Comment by mustanggb** [comment]
Submitted a pull request with an alternative approach of fixing this.
