### ISSUE TITLE
How do I enable full-network routing through Tor?

### ISSUE THREAD

**Issue by spikespaz** [dperson/torproxy#30]
It is stated [here](https://github.com/dperson/torproxy#how-to-use-this-image) that I should be able to use [this script](https://github.com/dperson/torproxy/blob/master/tor-route-all-traffic.sh) to route all traffic through Tor. Where is this script and how would I change the command to start this on container creation?

I've already set `--net=host`.

**Comment by dperson** [comment]
The script is in the GitHub repo, as linked above. It has to be run on your host really, as I understand it.
