### ISSUE TITLE
[warn] Socks version not recognized

### ISSUE THREAD

**Issue by adolfaka** [dperson/torproxy#33]
**command:** `sudo docker run -it -p 9050:9050 -d dperson/torproxy -p *** -l "NL}, {FR}, {GB}, {CY"`

**output:**
```
...
Oct 04 16:35:16.000 [notice] Bootstrapped 100%: Done
Oct 04 16:35:17.000 [warn] Socks version 67 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
Oct 04 16:35:18.000 [warn] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
Oct 04 16:35:18.000 [warn] Socks version 67 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
```

**Comment by dperson** [comment]
I'm not getting those errors in my logs. Are you doing anything else (trying to connect through it, etc.)?

**Comment by dperson** [comment]
I'm going to close this because there's been no response. If you're still having a problem, feel free to reply to this and I'll try to help you out.
