### ISSUE TITLE
update to 4.1

### ISSUE THREAD

**Issue by valsha** [dperson/torproxy#34]
Good day, can you update tor to last stable version 4.1.x
Thank you.

**Comment by valsha** [comment]
Hi, updated today image 
"Oct 17 09:01:25.458 [notice] Tor 0.3.5.8 running on Linux"

**Comment by dperson** [comment]
Hey, sorry. I had checked the Alpine Linux package repos and saw that 4.1 was in there, I'd missed that it was in the 'edge' repo not for the released build. So it won't be in the container until Alpine's next release.
