### ISSUE TITLE
Node.js Error: request timed out

### ISSUE THREAD

**Issue by loretoparisi** [dperson/torproxy#38]
When In Node.js using built-in `http` library and GET with headers

```
{
	headers: {
		Host: 'api.ipify.org'
	},
	host: '127.0.0.1',
	path: 'https://api.ipify.org/?format=json',
	timeout: 30000,
	method: 'GET',
	port: 8118
}
```

I get a `Error: request timed out`, while if using [global-tunnel](https://github.com/np-maintain/global-tunnel) configured as

```javascript
var globalTunnel = require('global-tunnel-ng');

    globalTunnel.initialize({
        host: 'localhost',
        port: 8118
    });
```
it works ok.

**Comment by dperson** [comment]
I've only ever done really light node.js development, and don't feel qualified to support it sorry.

**Comment by dperson** [comment]
If you're seeing strange behavior from curl, etc. then I will try to figure out what is going wrong. As it stands now, it seems you already have a work around for the issue.

**Comment by loretoparisi** [comment]
@dperson thank you, cURL works ok. Typically just using `Host` header as `host`, `port` and `path` in the http module options were enough to pass through the privoxy.
