### ISSUE TITLE
IP rotation

### ISSUE THREAD

**Issue by petergombos** [dperson/torproxy#4]
Is there a way to set NewCircuitPeriod when running the container?

**Comment by dperson** [comment]
There is in the just pushed version. =) If you set an environment variable that starts with `TOR_` it will be set in the configuration file. IE, `-e TOR_NewCircuitPeriod=10` will add (or change if the configuration if it exists) to `NewCircuitPeriod 10`.

It will also work for other settings. It hasn't had much testing yet...
