### ISSUE TITLE
changing bridge in docker version on synology

### ISSUE THREAD

**Issue by rp4k** [dperson/torproxy#42]
hello i am in china and i need to change what bridge it uses in the docker ,  i downloaded your docker and installed it already but i do not know how to configure it to use a different bridge then default.  default bridges can not be reached in china, so is there a way to set it to use maybe the obfs4  and built-in bridge.  because i am in a censored country.

**Comment by rp4k** [comment]
for Environment  can i use a command  
TOR?????  to change the bridge from default to obfs4

**Comment by dperson** [comment]
Unfortunately it doesn't look like Alpine has packaged the plugable transports (including obfs4) so it won't work. Sorry.
