### ISSUE TITLE
Default configuration warnings, security problem in local network?

### ISSUE THREAD

**Issue by malger** [dperson/torproxy#44]
When i start the container i get the warnings

```
Apr 26 15:57:11.260 [notice] Read configuration file "/etc/tor/torrc".
Apr 26 15:57:11.267 [warn] You specified a public address '0.0.0.0:9040' for TransPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Apr 26 15:57:11.268 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Apr 26 15:57:11.268 [warn] You specified a public address '0.0.0.0:9040' for TransPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
```

is that a problem in a local network? 
Additionall info:
I dont have any kind of port forwarding enabled in my router.
I use macvlan network to assign the docker container to an ip address in the local network.

**Comment by dperson** [comment]
It's on a private docker network, only other docker containers could get to it until you add a `-p` (port forward) argument to docker. Without it, you can't share it to your normal network only other containers that shared the docker containers network stack.
