### ISSUE TITLE
control.authcookie location

### ISSUE THREAD

**Issue by dmp1ce** [dperson/torproxy#5]
Why did you put the `control.authcookie` in `/etc/tor/run`? Can it go in `/var/run/tor` instead?

I'm trying to connect another container to torproxy and it wants to look in `/var/run/tor` for `control.authcookie`.

**Comment by dperson** [comment]
To keep files that you probably want to keep around in one place, so fewer volumes would need to be created. Is there a good reason not to?

**Comment by dmp1ce** [comment]
That's fine. I decided to create my own Tor container because I had some other requirements for what I'm building.

Thanks for your time.
