### ISSUE TITLE
How to route traffic for another docker app?

### ISSUE THREAD

**Issue by machinexa2** [dperson/torproxy#69]
I run app through docker run appcompany/app, how to proxy it through tor using your app. I know a app called proxychains docker run appcompany/app but it does only for normal proxies

**Comment by Guilvareux** [comment]
You should be able to use
```--net=<container_name>```
I've only done this with VPNs but in theory you should be able to use the torproxy network stack from another container by including it in the docker run command. 
Have a look at the Network Settings section
[Docker run reference](https://docs.docker.com/engine/reference/run/)

**Comment by machinexa2** [comment]
thanks
