### ISSUE TITLE
unraid

### ISSUE THREAD

**Issue by goverton** [dperson/torproxy#8]
Cant get this running on Unraid. This is what my run commnd looks like:

`docker run -d --name="Torproxy" --net="bridge" -e TZ="Europe/London" -e HOST_OS="unRAID" -e "USERID"="99" -e "GROUPID"="100" -e "TORUSER"="root" -p 8118:8118/tcp -p 9050:9050/tcp -p 9051:9051/tcp -it dperson/torproxy`

And this is the resulting log:

`3:18:08.840 [notice] Tor v0.2.8.9 (git-cabd4ef300c6b3d6) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2j and Zlib 1.2.8.
3:18:08.840 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
3:18:08.840 [notice] Read configuration file "/etc/tor/torrc".
3:18:08.849 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
3:18:08.851 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
3:18:08.851 [notice] Opening Socks listener on 0.0.0.0:9050
3:18:08.851 [notice] Opening DNS listener on 127.0.0.1:5353
3:18:08.851 [notice] Opening Transparent pf/netfilter listener on 127.0.0.1:9040
3:18:08.851 [notice] Opening Control listener on 127.0.0.1:9051
3:18:08.000 [warn] Couldn't open "/etc/tor/run/control.authcookie.tmp" (/etc/tor/run/control.authcookie) for writing: Permission denied
3:18:08.000 [warn] Error writing auth cookie to "/etc/tor/run/control.authcookie".
3:18:08.000 [warn] Error creating control cookie authentication file.
3:18:08.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying. (on Tor 0.2.8.9 )`

**Comment by dperson** [comment]
Oops, the startup script wasn't `chown`ing `/etc/tor` along with the rest of the tor daemons files. Try the version I just pushed. Thanks for the bug report.
