### ISSUE TITLE
How identities works

### ISSUE THREAD

**Issue by iBobik** [dperson/torproxy#9]
Do it have one identity (circuit, IP) for a whole time it is started or it switch identity for each request? How to request new identity or handle multiple identities?

**Comment by dperson** [comment]
It's just tor from the debian repositories, I'm not changing the configuration for circuits at all. It's my understanding that they normally persist for approximately 10 minutes, then a new circuit is established.

**Comment by sayhicoelho** [comment]
@dperson Is there a way to force it?
